services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      SAMPLE_MODE: "true"
      SQLITE_DB_PATH: data/processed/public_safety_ops.sqlite
      MONGO_URI: mongodb://mongo:27017
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
