apiVersion: v1
kind: Service
metadata:
  name: public-safety-demand-service
  namespace: public-safety-demand-intelligence
spec:
  type: ClusterIP
  selector:
    app: public-safety-demand-app
  ports:
    - name: http
      port: 80
      targetPort: 8501
